# Generated by Django 2.2.3 on 2019-11-06 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mango', '0014_auto_20191106_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Name')),
                ('start', models.DateField(blank=True, verbose_name='Start Date')),
                ('end', models.DateField(blank=True, verbose_name='End Date')),
                ('AddProject', models.TextField(blank=True, verbose_name='Contributors')),
                ('inserted_timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MangoAbouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MangoAbout',
        ),
    ]
