# Generated by Django 2.2.3 on 2019-11-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0015_auto_20191106_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproject',
            old_name='AddProject',
            new_name='contributors',
        ),
        migrations.AddField(
            model_name='addproject',
            name='category',
            field=models.TextField(blank=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='addproject',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='addproject',
            name='resources',
            field=models.TextField(blank=True, verbose_name='Resources'),
        ),
    ]
